{
  aggregate ? import ./aggregate.nix { },
}:
let
  joinLines = lines: builtins.concatStringsSep "\n" lines;

  suffixOrEmpty = attrs: if attrs ? suffix then attrs.suffix else "";

  renderHeroLink =
    link:
    if link.kind == "badge" then
      "[![${link.alt}](${link.image})](${link.href})${suffixOrEmpty link}"
    else if link.kind == "image" then
      "![${link.alt}](${link.image})${suffixOrEmpty link}"
    else
      "[${link.label}](${link.href})${suffixOrEmpty link}";

  renderContactLink = link: "* [${link.label}](${link.href})";

  renderCard = card: "![${card.label}](${card.image})";

  renderDetails =
    detail:
    joinLines (
      [
        "<details><summary>${detail.summary}</summary>"
        ""
      ]
      ++ map renderCard detail.cards
      ++ [ "</details>" ]
    );

  heroBadges = if aggregate.hero ? badges then aggregate.hero.badges else [ ];

  titleBlock = joinLines (
    [
      "<!-- DO NOT EDIT: generated by Nix -->"
      "![${aggregate.hero.image.alt}](${aggregate.hero.image.src})"
      "# ${aggregate.hero.heading.emoji} ${aggregate.hero.heading.text}"
    ]
    ++ map renderHeroLink heroBadges
    ++ map renderHeroLink aggregate.hero.links
  );

  contactBlock = joinLines (
    [
      "# ${aggregate.contact.heading}"
    ]
    ++ map renderContactLink aggregate.contact.links
  );

  statsBlock = joinLines (
    [
      "# ${aggregate.stats.heading}"
    ]
    ++ map renderCard aggregate.stats.cards
    ++ map renderDetails aggregate.details
  );
in
joinLines [
  titleBlock
  ""
  contactBlock
  ""
  statsBlock
] + "\n"
